[package]
name = "forex"
version = "0.1.0"
authors = ["root <root@root>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gilrs = "0.7.4"
#udev = "0.3.0"
jack = "0.6"
#crossbeam-channel = "0.4.2"
